services:
  app:
    build: ./app/
    image: event-planner-api:latest
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database

  web:
    image: nginx:1.26.3-alpine3.20-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - database

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-volumes:/var/lib/rabbitmq
    restart: on-failure


  database:
    image: postgres:13.18-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ml:
   build: ./ml/
   image: tree-detector:latest
   volumes:
     - ./ml:/ml
   depends_on:
     - database
     - rabbitmq

  web_ui:
    build: ./web_ui/
    image: latex-to-text-web-ui:latest
    volumes:
      - ./web_ui:/web_ui
    ports:
      - 8501:8501
    depends_on:
      - app

volumes:
  rabbitmq-volumes:
  postgres-data: